# Uncomment the next line to define a global platform for your project
# platform :ios, '11.3'

target 'swf-RaderChart-demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swf-RaderChart-demo
  pod 'Charts'

  target 'swf-RaderChart-demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
